#7 changed semantic versioning regex check

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -46,22 +46,18 @@ release_job:
   tags:
     - docker-build
   stage: deploy
+  # The job is run on tag commits only
   only:
     - tags
-  rules: 
-  #If the commit is a tag commit, we run this stage
-    # - if: $CI_COMMIT_TAG 
-    # - if: "$CI_COMMIT_TAG =~ '^v\\d+\\.\\d+\\.\\d+$'"
   script:
     - |
-      if [[ "$CI_COMMIT_TAG" =~ ^v\d+\.\d+\.\d+$ ]]; then
-        echo "Semantic versioning check passed for tag: $CI_COMMIT_TAG"
-        # Add your deployment logic here
+      if [[ "CI_COMMIT_TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+        echo "Version is valid."
         docker build -f Dockerfile -t "$CI_REGISTRY_IMAGE":"$CI_COMMIT_TAG" .
         docker push "$CI_REGISTRY_IMAGE":"$CI_COMMIT_TAG"
       else
-        echo "Tag $CI_COMMIT_TAG does not follow semantic versioning"
-        exit 1  # Exit with non-zero status to fail the job
+        echo "Version is invalid."
+        exit 1
       fi
   # Ensure that we only deploy when the project could be built and tested successfully
   needs:
